apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: computeinstance
  labels:
    crossplane.io/xrd: xcomputeinstances.example.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: example.com/v1alpha1
    kind: xcomputeinstance
  resources:
  - name: compute
    base:
      apiVersion: compute.gcp.jet.crossplane.io/v1alpha2
      kind: Instance
      spec:
        forProvider:
          networkInterface:
            - network: default
          bootDisk:
            - initializeParams:
                - image: projects/debian-cloud/global/images/debian-11-bullseye-v20220822
        providerConfigRef:
          name: 'default'
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.name

    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.zone
      toFieldPath: spec.forProvider.zone

    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.machineType
      toFieldPath: spec.forProvider.machineType
      transforms:
        - type: map
          map:
            small: e2-standard-2
            medium: e2-standard-4
            big: e2-standard-8

  - name: filestore
    base:
      apiVersion: filestore.gcp.jet.crossplane.io/v1alpha1
      kind: Instance
      spec:
        forProvider:
          fileShares:
            - capacityGb: 1024
              name: filestore
          name: filestore
          networks:
            - network: default
              modes:
                - MODE_IPV4
          tier: BASIC_HDD
        providerConfigRef:
          name: 'default'
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.zone
      toFieldPath: spec.forProvider.zone

